### ISSUE TITLE
[非issue]这个包相比jieba.el的优势？

### ISSUE THREAD

**Issue by qingshuizheng** [ginqi7/deno-bridge-jieba#7]
大佬好！
不懂就问，这个包和jieba.el有什么优势？
用deno实现，速度更优？

**Comment by qingshuizheng** [comment]
刚注意到论坛里有讨论，看得差不多了，打扰啦～～～

留链接给有需要的人：
https://emacs-china.org/t/deno-bridge/22419/63

**Comment by ginqi7** [comment]
我实现的时候，参考了 jieba.el 的功能。可能性能会好一些，但不确定。核心逻辑基本都是一样的。
把复杂的计算逻辑从 Emacs 里抽取出来，让外部应用运行。这样就可以让 Emacs 编辑时不卡顿。

主要是 denote-bridge 提供的和ts交互的接口比较简洁。

**Comment by qingshuizheng** [comment]
> 主要是 denote-bridge 提供的和ts交互的接口比较简洁

哈哈懂了，我看猫大也这么说。

话说我本来是纯elisp主义的，然后跟着你的包升级着升级着，发现emacs和外部交互一下，突然万物互联了。

**Comment by ginqi7** [comment]
纯elisp对elisp的编程能力要求有点高，有些功能用elisp实现会比较困难。还有就是不能把运算量大的工作放在elisp当中，否则卡。

**Comment by qingshuizheng** [comment]
嗯，lsp-bridge 原理把我征服了：https://manateelazycat.github.io/emacs/2022/06/26/why-lsp-bridge-not-use-capf.html
